### ISSUE TITLE
SSL truststore options no longer used

### ISSUE THREAD

**Issue by puremourning** [rundeck/packaging#4]
https://github.com/rundeck/packaging/blob/45e3470181d184f3ea947ad6d1e2183234d35a0b/lib/common/etc/rundeck/profile#L46

Why are these no longer referenced ?

After upgrading to rundeck v3.<latest> from v2.11.10, our active directory logon no longer works because it is not loading the truststore anymore.

Previously it was loaded: https://github.com/rundeck/rundeck/blob/release-2.11/packaging/root/etc/rundeck/profile#L79

Are we expected to configure this manually by overriding `RDECK_JVM_SETTINGS` now ? It's not in the upgrade guide. Let me know if i should raise with pro support instead.

**Comment by puremourning** [comment]
cc @shedplant, @richiereynolds

**Comment by sjrd218** [comment]
@puremourning The Rundeck 3.x SSL configuration works different than the 2.x version. We tried to maintain compatibility, but you may have found a place where it fell through. Please raise an issue with support so that we can help you get it working.

**Comment by puremourning** [comment]
Is the migration documented? I read the [upgrade guide](https://docs.rundeck.com/docs/upgrading/upgrade-to-rundeck-3.x.html) but didn't see anything.

**Comment by sjrd218** [comment]
There's code in Rundeck 3 that was supposed to apply the old 2.x style configs. The ideal situation was that the upgrade was transparent to the user.
